name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  http: ^1.3.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/profile.png
  - assets/images/profile2.jpg
  - assets/images/profile3.png
  - assets/images/afc/
  - assets/images/fika/
  - assets/images/gts/
  - assets/images/vts/
  - assets/images/skills/
  - assets/images/muslim/
  - assets/docs/curriculumvitae.pdf

  fonts:
  - family: Poppins
    fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700

